os:
  - linux

dist: trusty

language : c

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - sudo apt-get install valgrind

script:
  - make
  - make test
