os:
  - linux
  - osx

dist: trusty

language : c

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install valgrind ; fi

script:
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then make test ; fi
